# Introduction {#intro}

The monitoring of sleep and the estimation of sleep quality has become relevant in recent years due to research that has positively correlated poor sleep quality with various problems ranging from mild to serious. Minor and short-term problems include lack of concentration, difficulty remembering and learning new things and irritability, while more serious problems talk about hypertension, type II diabetes, Alzheimer's and other chronic degenerative diseases.

The intention of this work is to construct a model that infer the quality of  sleep of a person from the factors of the hygiene of the sleep. The literature discusses at least 21 factors of sleep hygiene that should be considered when studying the possible causes of a sleep disorder, physicians conduct interviews and apply questionnaires to their patients to investigate behaviors that favor or impair sleep quality, and from there they begin to generate a clinical file that allows them to diagnose or move to a second stage of the protocol that consists of laboratory studies such as polysomnography or actigraphy.

This work is aimed at the prevention of poor sleep quality and the possible prevention of a sleep disorder. It is a question of constructing a model that estimates the quality of sleep from the most relevant factors of sleep hygiene for a given population. The model will acquire data of the hygiene of the dream by means of sensors coupled to the surroundings of the user and will make an estimation of the quality of the dream, later the user will give a qualification to his quality of dream of such form that day to day the model is Adjustment to the lifestyle and sleep patterns of the person and the person make changes to that lifestyle, following model recommendations in such a way that their quality of sleep is favored.

The first part in the construction of the model consisted of collecting information through clinically proven questionnaires on the perception of sleep quality and sleep hygiene in a sample of people as Section \@ref(data-adquisition) explains. With these data a study of the most relevant factors was made so that of the 21 original sleep hygiene factors that were taken from the literature, only the most relevant set was selected (see Section \@ref(feature-selection)). This will make it possible to implement the model in a real system because a reduced number of factors implies few sensors in the context of the user, which translates into less design complexity, less intrusiveness and less infrastructure cost.


After selecting the most relevant factors for the estimation of sleep quality, we proceeded to test the model using the cross-validation technique. This was done with two purposes. The first one was to validate that the selection of factors was successful in verifying that with the subset of variables the model predicts with more efficiency the quality of sleep than when using the total factors. Second, this work was useful to obtain the first performance analysis of three supervised automated learning techniques to generate predictive models. The techniques tested were artificial neural networks (ANNs), logistic regression with regularization (LR) and vector supported machines (SVM). The three techniques had an efficient behavior as can be seen in the Section \@ref(evaluation-of-efficiency) and are candidates for any of them being chosen to be the basis of the model.
